### ISSUE TITLE
Stencil perf best practices

### ISSUE THREAD

**Issue by jgw96** [Fdom92/personal-web-site#1]
- put all components needed for the first view in one bundle. This will decrease the amount of network requests needed to render the first view. So `<web-header />`, `<my-info />`, `<my-projects />`, `<my-experience />`, `<my-cv />`,`<my-hobbies />` and `<web-footer />` should all be in the same bundle. Everything else can be lazy loaded

- use [link rel=preload](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content) to preload your first bundles JS and css

- make sure your doing a prod build (npm run build) before you deploy to firebase

There are some more in depth things you could do if this does not get you to a 100, but this should get you there pretty easily.

**Comment by Fdom92** [comment]
Hi @jgw96 thanks for this, i made some refactors on styles and modify the bundles and this is what i get now thanks to you! 🎉 🎉 🎉 

<img width="839" alt="screen shot 2017-09-06 at 18 59 24" src="https://user-images.githubusercontent.com/7361737/30124498-a64d887c-9335-11e7-80ac-bba4eae05127.png">
